title: Catatan Nouvalalg
email: your-email@example.com
description: >-
  Blog pribadi berisi catatan belajar, pengembangan diri, dan dokumentasi ringan.
baseurl: "" 
url: "https://nouvalalg.github.io"
theme: minima
plugins:
  - jekyll-feed
