title: "Blog Nouvalalg"
email: vallzcrzy@email.com
description: >-
  Blog pribadi tentang catatan PKL, pengembangan diri dan teknologi.
baseurl: "" # leave this blank for GitHub Pages
url: "https://nouvalalg.github.io"
theme: minima

# social
author:
  name: Nouvalalg
  email: vallzcrzy@email.com
  instagram: Fllyyaaaaa_

plugins:
  - jekyll-feed
